export * from './config/url.config'
export * from './services/data.service'
export * from './components/app-loader/app-loader.component'
export * from './components/no-result/no-result.component'
export * from './pipe/remove-duplicates.pipe'
export * from './core.module'